### ISSUE TITLE
eus_qp cannot compile on indigo/14.04

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_control#208]
```
In file included from /home/jskuser/ros/indigo/src/jsk-ros-pkg/jsk_control/eus_qp/src/qp_lib.cpp:5:0:
/home/jskuser/ros/indigo/src/jsk-ros-pkg/jsk_control/eus_qp/3rdparty/eiquadprog.hpp: In function ‘Scalar Eigen::distance(Scalar, Scalar)’:
/home/jskuser/ros/indigo/src/jsk-ros-pkg/jsk_control/eus_qp/3rdparty/eiquadprog.hpp:94:7: error: ‘abs’ is not a member of ‘Eigen::internal’
  a1 = internal::abs(a);
       ^

```

**Comment by garaemon** [comment]
fixed
